### ISSUE TITLE
Comment body text CSS causes warning

### ISSUE THREAD

**Issue by amolenaar** [gaphor/gaphor#1598]
### Describe the bug

Create a model with an element and the following CSS:

```css
comment[body^="todo"] {
  background-color: orange;
}
```

This will raise a warning 

```
gaphor.core.modeling.diagram WARNING Can not make a string out of <gaphor.diagram.shapes.Text object at 0x7fc769c9fc40>, returning "". Please raise an issue.
```

### Expected behavior

No warning. The functionality seems to work fine.

### Version
Version of Gaphor: 2.10 / main
