### ISSUE TITLE
Add to Style Sheet button adds new CSS rules when ones already exist

### ISSUE THREAD

**Issue by vanillajonathan** [gaphor/gaphor#3941]
### Describe the bug
Every time you click on the 'Add to Style Sheet' button it adds a new CSS rule instead instead of merging the properties with an existing rule.

### To Reproduce
1. Click on anything in the diagram
2. Click on the 'Open Style Editor' button
3. Click twice on the 'Add to Style Sheet' button
4. Inspect the style sheet

### Expected behavior
When an existing CSS rule exists it should append properties to that CSS rule and overwrite existing properties.
```css
pseudostate {
  border-radius: 3.0;
  color: rgba(181, 131, 90, 1.0);
}
```

### Current bad behavior
```css
pseudostate {
  color: rgba(181, 131, 90, 1.0);
}

pseudostate {
  border-radius: 3.0;
}

```

### OS
- [x] Linux (Ubuntu)
- [ ] macOS
- [ ] Windows

### Version
Version of Gaphor: 3.1.0
